name: Test-CI


on:
  push:
    branches: [ main, feature/workflows-caching ]
  pull_request:
    branches: [ main, feature/workflows-caching ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run Tests
        run: ./gradlew test
